### ISSUE TITLE
Email verification upon registration sucess.

### ISSUE THREAD

**Issue by obafemiolorungbon** [zurichat/zc_main#150]
Verify the user email by sending a verification link if their registrations succeeds.

**Comment by AlanDouglasDan** [comment]
This issue is handled by me (AlanDouglasDan)

**Comment by AlanDouglasDan** [comment]
I added two functions to the lib folder that handles email verification after a user has been validated to login. The first function sends the verification link to the user to click and it depends on a mailFunc(), imported from my team members file and the second function is one that would be called to verify the mail by comparing two token values for equality

**Comment by AlanDouglasDan** [comment]
The issue I took up is one that sends a mail to the user to verify his email address and cannot be implemented until the registration form has been fully implemented but my solution has been approved by my team lead and it shows the two functions exported in email_verify.js works perfectly and will be properly integrated when the registration form is complete but the live testing link will be https://zuri.chat/signup
My slack username is @AlanDouglas
