### ISSUE TITLE
Logging information of new device signed in.

### ISSUE THREAD

**Issue by bolubee101** [zurichat/zc_main#153]
When a user signs in to a workspace on a new device, the device information should be logged, and if necessary the user can be notified.

**Comment by bolubee101** [comment]
Testing linking on 

https:zuri.chat/api/test/deviceinfo

**Comment by bolubee101** [comment]
Testing linking on [https:zuri.chat/api/test/deviceinfo](https:zuri.chat/api/test/deviceinfo)

**Comment by markessien** [comment]
Ticket is closed

**Comment by bolubee101** [comment]
> Ticket is closed

It has been reopened. 

Testing linking on

[https://zuri.chat/api/test/deviceinfo](https://zuri.chat/api/test/deviceinfo)

**Comment by bolubee101** [comment]
Testing link on
https://zuri.chat/api/test/deviceinfo
