### ISSUE TITLE
Email Registration Alert!!!

### ISSUE THREAD

**Issue by Onagie5** [zurichat/zc_main#183]
As a user, I would like to receive an email after registration to confirm my email address. So as to give me a guarantee that my registration went through

**Comment by optimistictech** [comment]
I will work on this

**Comment by Comurule** [comment]
## Steps to achieve this::

- install `nodemailer` as a dependency in the repo, if it's not there already
- write a script that sets up `node mailer` and sends mails(this will be your `sendMail` script). Check [this w3 schools](https://www.w3schools.com/nodejs/nodejs_email.asp) resource for gmail account setup, or [this,](https://jasonwatmore.com/post/2020/07/20/nodejs-send-emails-via-smtp-with-nodemailer) if you prefer hardcore...lol
- Your script should be able to take in the necessary parameters to send a mail to a client.
- Call that `sendMail` function wherever it's needed in the repo, passing the necessary parameters.
