### ISSUE TITLE
Added Song Notification

### ISSUE THREAD

**Issue by Onagie5** [zurichat/zc_main#190]
As a user, I would like to get a pop up confirming that I have added a song to the playlist in the music room, to keep me aware and prevent me from repeating that action again

**Comment by code-pace** [comment]
I will work on this

**Comment by code-pace** [comment]
### Team Voltaire
No live url because its not yet merged so I included a screenshot👇
![Zuri Chat - Google Chrome 9_3_2021 1_16_22 PM](https://user-images.githubusercontent.com/81013036/132214760-b15ee9cd-440b-4e86-8687-ef111cce0367.png)
