### ISSUE TITLE
Email Notification

### ISSUE THREAD

**Issue by Onagie5** [zurichat/zc_main#198]
As a user, I would like to receive an email notification whenever a task is being dropped. So I wouldn't miss out important update or information that require my attention

**Comment by optimistictech** [comment]
I will work on this.

**Comment by siryus95** [comment]
I will be working on this issue

**Comment by Comurule** [comment]
What do you mean by task?.... does this mean any notification at all or a task notification(to-do plugin).... @Onagie5

**Comment by siryus95** [comment]
I mean email notification
