### ISSUE TITLE
Build crud API for workspace

### ISSUE THREAD

**Issue by Tech-sis** [zurichat/zc_main#224]
Create, Read, Update, Delete the workspace controller

**Comment by Falence** [comment]
- slack name: **falenceLemungoh**
- Team: Aristotle

Implements CRUD API endpoints for workspace that allows users create, get, update and delete a workspace
- Live link: [GET] [Get all workspaces](https://zuri.chat/api/workspaces)
- Live link: [GET] [Get a workspaces](https://zuri.chat/api/workspaces/61325d1d7627a649e1b6715d)
- Live link: [POST] [Create a workspaces](https://zuri.chat/api/workspaces)
- Live link: [UPDATE] [Update a workspaces](https://zuri.chat/api/workspaces/61325d1d7627a649e1b6715d) 
- Live link: [DELETE] [Delete a workspaces](https://zuri.chat/api/workspaces/61325d1d7627a649e1b6715d)

- PR: [Here](https://github.com/zurichat/zc_main/pull/824)

**Comment by markessien** [comment]
This architecture is wrong. Zuri.chat is not supposed to have a separate api. The api for zurichat is zuricore

**Comment by Falence** [comment]
> This architecture is wrong. Zuri.chat is not supposed to have a separate api. The api for zurichat is zuricore

Alright. Thank you. I will fix it, sir.
