### ISSUE TITLE
Create a name for each company goals

### ISSUE THREAD

**Issue by Ojo-Triumph** [zurichat/zc_main#233]
-      The title of the company goals must be 
      accompanied by the name of the person 
      who the task has been assigned to

-     Every goal must have a deadline beneath it

-     The goals for each individuals must also 
      have a check box to mark completed or 
      abandoned or not done within a set period 
      of time

**Comment by Khrees2412** [comment]
Which team owns the issue?? Add a label

**Comment by Ojo-Triumph** [comment]
I made it in the wrong place
