### ISSUE TITLE
Access controller to manage routes

### ISSUE THREAD

**Issue by MvthvrMagnolia** [zurichat/zc_main#321]
Global route access controller, to restrict access to different routes

**Comment by VikMaamaa** [comment]
i am working on this

**Comment by VikMaamaa** [comment]
i am working on this

**Comment by VikMaamaa** [comment]
Although i already worked on #368 and #364(cookie issue)
i work on issue #321
Test Link
https://zuri.chat/api//test/route-access-controller

The controller restricts access to any route it is attached, throwing an error for an unspecified type of users, for that particular route
