### ISSUE TITLE
Password preference

### ISSUE THREAD

**Issue by MvthvrMagnolia** [zurichat/zc_main#427]
a password must be a mixture of numbers,letters and special characters

**Comment by ickynavigator** [comment]
@MvthvrMagnolia I noticed you assigned yourself when already opened a pull request to close this issue

**Comment by MvthvrMagnolia** [comment]
All isssues remain open till verified by a mentor or PR manager

**Comment by markessien** [comment]
No testing link

**Comment by ickynavigator** [comment]
@markessien no testing link because it has not been implemented by the sign up page yet
