### ISSUE TITLE
Footer Components

### ISSUE THREAD

**Issue by Tech-sis** [zurichat/zc_main#54]
Add a newsletter sign up form so users can subscribe and stay up to date with Zuri.

[Live link](https://zuri.chat/contact-us)
Added footer components for all external pages.  [PR link](https://github.com/zurichat/zc_main/pull/705)

**Comment by dantanee** [comment]
built a footer component that can be integrated by all external pages.
[link to footer integrated by features page](https://zuri.chat/features)
