### ISSUE TITLE
Set up Security for the server 

### ISSUE THREAD

**Issue by obafemiolorungbon** [zurichat/zc_main#568]
Using Helmet or any service, set up security for the node server

**Comment by arabog** [comment]
I will solve this issue

**Comment by arabog** [comment]
the link: https://zuri.chat/
(using google chrome) Right click on https://zuri.chat/ page and click inspect --> Network --> Refresh the page with the Develop Tool open --> Click any of the item under Name section --> check the Response Headers (on the right side of the Name section)
Thank you.

**Comment by markessien** [comment]
Okay :+1:
