### ISSUE TITLE
Career page

### ISSUE THREAD

**Issue by Tech-sis** [zurichat/zc_main#58]
A user should see a listing of open roles for work at zurichat; including descriptions and requirements for each role that is open.

**Comment by Cyanhead** [comment]
I worked on section 2 of the careers page of the external pages. The other sections have not been merged, so I can't close the issue yet, but only contribute to it

Live link: https://zuri.chat/careers

![Screenshot_mobile](https://user-images.githubusercontent.com/67376168/132065756-bb6d5bc8-0559-4393-bc39-4ea188663f73.png)
![Screenshot_desktop](https://user-images.githubusercontent.com/67376168/132065759-1f4b75f2-9d56-46ff-a23b-02b3d6bc798f.png)
