### ISSUE TITLE
interactive login form

### ISSUE THREAD

**Issue by MvthvrMagnolia** [zurichat/zc_main#597]
user should be able to input their details in the login form https://zuri.chat/login

**Comment by sammiearchie77** [comment]
I have done this

**Comment by T-manuel** [comment]
I tested the login and its not looking nice on my device, please how do I work on it... 
![Screenshot_20210906-072353](https://user-images.githubusercontent.com/26921479/132170143-b7dfc40d-39d4-414a-94f1-109b05fb793c.png)

![Screenshot_20210906-072414](https://user-images.githubusercontent.com/26921479/132170120-91d123ed-bba6-4ca4-b7e4-a90e47050637.png)
 
![Screenshot_20210906-072339](https://user-images.githubusercontent.com/26921479/132170150-024a0587-aede-4532-84ee-ca3bb234b6b2.png)


Figma page

![Screenshot_20210906-070720](https://user-images.githubusercontent.com/26921479/132170274-40b9d8cb-471f-430e-9451-ea9d88479b8e.png)
![Screenshot_20210906-070508](https://user-images.githubusercontent.com/26921479/132170282-e1257d4f-3f4f-44d8-8957-c074caef939e.png)

**Comment by sammiearchie77** [comment]
I'll refactor it. Again, I still don't know why my codes is not the server
updated code
