### ISSUE TITLE
Get user details endpoint

### ISSUE THREAD

**Issue by Khrees2412** [zurichat/zc_main#762]

**Comment by Temilade05** [comment]
An api that gets the current logged in user based on the token sent and the details returned from zuri core.

Currently returns dummy data as zuri core doesn't have this user endpoint up and running yet.

**Comment by Temilade05** [comment]
Live link: https://zuri.chat/api/test/get-user

Slack name: Temi05

Feature returns the user info. Currently returning dummy data.
