### ISSUE TITLE
Deactivation of account

### ISSUE THREAD

**Issue by Elijah699** [zurichat/zc_main#888]
A user should be able to deactivate their account

**Comment by sammiearchie77** [comment]
Boss, I can't add label, strange

**Comment by sammiearchie77** [comment]
Boss, I can't add label, strange

**Comment by Elijah699** [comment]
https://github.com/zurichat/zc_main/pull/914

**Comment by Elijah699** [comment]
Figma Link: https://www.figma.com/file/QQtqQPdoRW9XZeD8Ny6u8w/Team-Einstein?node-id=0%3A1

Live link: https://zuri.chat/deactivate-account

Pull request: https://github.com/zurichat/zc_main/pull/914
